# Generated by Django 2.1.7 on 2019-05-08 07:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('amount', models.DecimalField(decimal_places=5, max_digits=10)),
                ('trans_type', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Liq Pay'), (2, 'Счет фактура')], null=True)),
                ('source', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Покупка базового пакета'), (2, 'Покупка полного пакета'), (3, 'Пополнение баланса'), (4, 'Вывод средств'), (5, 'Перевод денег на баланс после успешного заказа'), (6, 'Списание денег с баланса после успешного заказа')], null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Транзакция оплаты',
                'verbose_name_plural': 'Транзакции оплат',
            },
        ),
    ]
