# Generated by Django 2.1.7 on 2019-05-08 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='err_description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание ошибок'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='is_has_error',
            field=models.BooleanField(default=False, verbose_name='Наличие ошибок'),
        ),
    ]
