# Generated by Django 2.1.7 on 2019-05-08 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_auto_20190508_1101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='is_has_error',
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='status',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Статус платежа'),
        ),
    ]
