# Generated by Django 2.1.7 on 2019-05-08 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_auto_20190508_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='is_valid_signature',
            field=models.BooleanField(default=True, verbose_name='Проверка сигнатуры'),
        ),
    ]
