# Generated by Django 2.1.7 on 2019-04-03 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreSliderImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='users/company/store/slider', verbose_name='Картинка для слайдера')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slider_images', to='users.MyStore')),
            ],
        ),
    ]
