# Generated by Django 2.1.7 on 2019-04-08 12:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190401_0729'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usernotification',
            options={'verbose_name': 'Уведомление пользователя', 'verbose_name_plural': 'Увидемления пользователя'},
        ),
        migrations.AddField(
            model_name='customuser',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Company', verbose_name='Менеджер'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='users.Company', verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(blank=True, max_length=200, null=True, verbose_name='Емейл'),
        ),
        migrations.AlterField(
            model_name='company',
            name='manufacturer',
            field=models.BooleanField(default=False, verbose_name='Производитель'),
        ),
        migrations.AlterField(
            model_name='company',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='URL-путь'),
        ),
        migrations.AlterField(
            model_name='company',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владецел компании'),
        ),
        migrations.AlterField(
            model_name='company',
            name='web_site',
            field=models.URLField(blank=True, null=True, verbose_name='Веб-сайт'),
        ),
        migrations.AlterField(
            model_name='companypitch',
            name='company',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Company', verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True, verbose_name='Емейл'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='patronymic',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='mystore',
            name='call_back',
            field=models.CharField(blank=True, choices=[('YES', 'Включена'), ('NO', 'Выключена')], max_length=3, null=True, verbose_name='Функция Сall-back'),
        ),
        migrations.AlterField(
            model_name='mystore',
            name='domain_name',
            field=models.URLField(blank=True, null=True, verbose_name='Имя домена'),
        ),
        migrations.AlterField(
            model_name='mystore',
            name='domain_subdomain',
            field=models.CharField(blank=True, choices=[('DM', 'Домен'), ('SD', 'Поддомен')], max_length=2, null=True, verbose_name='Домен/поддомен'),
        ),
        migrations.AlterField(
            model_name='mystore',
            name='facebook',
            field=models.URLField(blank=True, null=True, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='mystore',
            name='instagram',
            field=models.URLField(blank=True, null=True, verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='mystore',
            name='linkedin',
            field=models.URLField(blank=True, null=True, verbose_name='Linkedin'),
        ),
        migrations.AlterField(
            model_name='mystore',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='users/company_logo', verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='navigation',
            name='navigation',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Раздел навигации'),
        ),
        migrations.AlterField(
            model_name='payercertificate',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payer_certificates', to='users.Company', verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='payerregister',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payer_registers', to='users.Company', verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='serviceindustry',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Company', verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='taxpayer',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tax_payers', to='users.Company', verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='ukrainestatistic',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ukraine_statistics', to='users.Company', verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='usernotification',
            name='cancel_order',
            field=models.BooleanField(default=False, verbose_name='Уведомление об отмене заказа'),
        ),
        migrations.AlterField(
            model_name='usernotification',
            name='new_message',
            field=models.BooleanField(default=False, verbose_name='Новое сообщение во внутреннем почтовом уведомлении'),
        ),
        migrations.AlterField(
            model_name='usernotification',
            name='sales_report',
            field=models.BooleanField(default=False, verbose_name='Уведомление о продажах'),
        ),
    ]
