# Generated by Django 2.1.7 on 2019-04-08 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_storesliderimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_pocket',
            field=models.CharField(blank=True, choices=[('BASE', 'Base'), ('FULL', 'Full'), ('NO', 'No')], default='BASE', max_length=10, null=True, verbose_name='Пакет услуг'),
        ),
    ]
