# Generated by Django 2.1.7 on 2019-03-20 11:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190320_0851'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_order', models.BooleanField(default=False, verbose_name='New order notification')),
                ('ttn_change', models.BooleanField(default=False, verbose_name='Change order TTN notification')),
                ('order_paid', models.BooleanField(default=False, verbose_name='Change order TTN notification')),
                ('sales_report', models.BooleanField(default=False, verbose_name='Sales report notification')),
                ('new_message', models.BooleanField(default=False, verbose_name='New message in internal mailing notification')),
                ('cancel_order', models.BooleanField(default=False, verbose_name='Cancel order notification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User notification',
                'verbose_name_plural': 'User notifications',
            },
        ),
    ]
