# Generated by Django 2.1.7 on 2019-04-15 11:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_mystore_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('CONTRACTOR', 'Поставщик'), ('PARTNER', 'Партнер')], default='CONTRACTOR', max_length=10),
            preserve_default=False,
        ),
    ]
