# Generated by Django 2.1.7 on 2019-03-20 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_usernotification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usernotification',
            name='new_order',
        ),
        migrations.AddField(
            model_name='usernotification',
            name='new_order_email',
            field=models.BooleanField(default=False, verbose_name='New order notification to email'),
        ),
        migrations.AddField(
            model_name='usernotification',
            name='new_order_tel',
            field=models.BooleanField(default=False, verbose_name='New order notification to tel'),
        ),
    ]
