# Generated by Django 2.1.7 on 2019-04-16 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190415_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companytype',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_types', to='users.Company'),
        ),
        migrations.AlterField(
            model_name='serviceindustry',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_industries', to='users.Company', verbose_name='Компания'),
        ),
    ]
