# Generated by Django 2.1.7 on 2019-04-15 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190415_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='web_site',
            field=models.URLField(blank=True, null=True, verbose_name='Веб сайт (url)'),
        ),
    ]
