# Generated by Django 2.1.7 on 2019-04-16 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190415_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='rozetka_password',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='rozetka_username',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
