# Generated by Django 2.1.7 on 2019-04-16 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190416_0900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activityareas',
            name='company',
        ),
        migrations.RemoveField(
            model_name='companytype',
            name='company',
        ),
        migrations.RemoveField(
            model_name='serviceindustry',
            name='company',
        ),
        migrations.AddField(
            model_name='company',
            name='activity_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_areas', to='users.ActivityAreas'),
        ),
        migrations.AddField(
            model_name='company',
            name='company_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_types', to='users.CompanyType'),
        ),
        migrations.AddField(
            model_name='company',
            name='service_industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_industries', to='users.ServiceIndustry'),
        ),
    ]
