# Generated by Django 2.1.7 on 2019-04-16 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20190416_0933'),
        ('users', '0006_auto_20190415_1444'),
    ]

    operations = [
    ]
