# Generated by Django 2.1.7 on 2019-04-17 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_merge_20190416_1020'),
    ]

    operations = [
    ]
