# Generated by Django 2.1.7 on 2019-04-17 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_merge_20190416_1020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mystore',
            name='company',
        ),
        migrations.RemoveField(
            model_name='mystore',
            name='user',
        ),
        migrations.RemoveField(
            model_name='navigation',
            name='store',
        ),
        migrations.RemoveField(
            model_name='phonenumber',
            name='store',
        ),
        migrations.RemoveField(
            model_name='storesliderimage',
            name='store',
        ),
        migrations.DeleteModel(
            name='MyStore',
        ),
        migrations.DeleteModel(
            name='Navigation',
        ),
        migrations.DeleteModel(
            name='PhoneNumber',
        ),
        migrations.DeleteModel(
            name='StoreSliderImage',
        ),
    ]
