# Generated by Django 2.1.7 on 2019-04-17 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20190416_1232'),
        ('users', '0008_merge_20190416_1020'),
    ]

    operations = [
    ]
