# Generated by Django 2.1.7 on 2019-04-17 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_merge_20190417_1356'),
    ]

    operations = [
    ]
