# Generated by Django 2.1.7 on 2019-04-17 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_merge_20190417_1356'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterPhoneNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона для футера')),
            ],
        ),
        migrations.CreateModel(
            name='HeaderPhoneNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона для хедера')),
            ],
        ),
        migrations.RemoveField(
            model_name='phonenumber',
            name='store',
        ),
        migrations.RemoveField(
            model_name='mystore',
            name='company',
        ),
        migrations.DeleteModel(
            name='PhoneNumber',
        ),
        migrations.AddField(
            model_name='headerphonenumber',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='header_phones', to='users.MyStore'),
        ),
        migrations.AddField(
            model_name='footerphonenumber',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='footer_phones', to='users.MyStore'),
        ),
    ]
