# Generated by Django 2.1.7 on 2019-04-18 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20190417_1448'),
        ('users', '0009_auto_20190417_1438'),
    ]

    operations = [
    ]
