# Generated by Django 2.1.7 on 2019-04-25 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20190422_1400'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='customuser',
        #     name='rozetka_old_orders_imported',
        #     field=models.BooleanField(default=False),
        # ),
    ]
