# Generated by Django 2.1.7 on 2019-04-25 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_remove_customuser_rozetka_old_orders_imported'),
    ]

    operations = [

    ]

