# Generated by Django 2.1.7 on 2019-05-07 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20190507_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mystore',
            name='domain_subdomain',
            field=models.CharField(blank=True, choices=[('DM', 'Домен'), ('SDM', 'Поддомен')], max_length=3, null=True, verbose_name='Домен/поддомен'),
        ),
    ]
