# Generated by Django 2.1.7 on 2019-05-08 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0009_pocketplan'),
        ('users', '0018_auto_20190507_0823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='user_pocket',
        ),
        migrations.AddField(
            model_name='customuser',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketplace.PocketPlan', verbose_name='Пакет услуг'),
        ),
        migrations.AlterField(
            model_name='mystore',
            name='domain_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Имя домена'),
        ),
    ]
