# Generated by Django 2.1.7 on 2019-05-13 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20190507_0823'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activityareas',
            options={'verbose_name': 'Сфера деятельности', 'verbose_name_plural': 'Сферы деятельности'},
        ),
        migrations.AlterModelOptions(
            name='certificate',
            options={'verbose_name': 'Свидетельсво', 'verbose_name_plural': 'Свидетельсва'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Компания партнера', 'verbose_name_plural': 'Компании партнеров'},
        ),
        migrations.AlterModelOptions(
            name='companypitch',
            options={'verbose_name': 'Питч компании', 'verbose_name_plural': 'Питчи компаний'},
        ),
        migrations.AlterModelOptions(
            name='companytype',
            options={'verbose_name': 'Тип компании', 'verbose_name_plural': 'Типы компаний'},
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterModelOptions(
            name='mystore',
            options={'verbose_name': 'Магазин партнера', 'verbose_name_plural': 'Магазины партнеров'},
        ),
        migrations.AlterModelOptions(
            name='passport',
            options={'verbose_name': 'Паспорт', 'verbose_name_plural': 'Паспорта'},
        ),
        migrations.AlterModelOptions(
            name='payercertificate',
            options={'verbose_name': 'Свидетельство плательщика ЕН', 'verbose_name_plural': 'Свидетельства плательщиков ЕН'},
        ),
        migrations.AlterModelOptions(
            name='payerregister',
            options={'verbose_name': 'Регистрация плательщика', 'verbose_name_plural': 'Регистрации плательщиков'},
        ),
        migrations.AlterModelOptions(
            name='serviceindustry',
            options={'verbose_name': 'Сфера услуг', 'verbose_name_plural': 'Сферы услуг'},
        ),
        migrations.AlterModelOptions(
            name='taxpayer',
            options={'verbose_name': 'Плательщик налогов', 'verbose_name_plural': 'Плательщики налогов'},
        ),
        migrations.AlterModelOptions(
            name='ukrainestatistic',
            options={'verbose_name': 'Статистика (комитет статистики Украины)', 'verbose_name_plural': 'Статистика (комитет статистики Украины)'},
        ),
        migrations.AlterField(
            model_name='mystore',
            name='domain_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Имя домена'),
        ),
    ]
