# Generated by Django 2.1.7 on 2019-05-08 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20190508_0837'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='package',
            new_name='user_pocket',
        ),
    ]
