# Generated by Django 2.1.7 on 2019-05-13 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20190513_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='nova_poshta_api_key',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
