# Generated by Django 2.1.7 on 2019-05-16 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_customuser_nova_poshta_api_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='cert_doc',
            field=models.FileField(blank=True, null=True, upload_to='companies/documents/certificates', verbose_name='Свидетельство о регистрации или выписка с ЕГРПОУ'),
        ),
        migrations.AlterField(
            model_name='payercertificate',
            name='payer_cert_doc',
            field=models.FileField(blank=True, null=True, upload_to='companies/documents/payer_certificates', verbose_name='Cвидетельство плательщика единого налога'),
        ),
        migrations.AlterField(
            model_name='payerregister',
            name='payer_reg_doc',
            field=models.FileField(blank=True, null=True, upload_to='companies/documents/payer_registers', verbose_name='Выписка из реестра плательщиков НДС'),
        ),
        migrations.AlterField(
            model_name='taxpayer',
            name='tax_doc',
            field=models.FileField(blank=True, null=True, upload_to='companies/documents/tax_payers', verbose_name='Справка 4 Учета плательщика налогов'),
        ),
        migrations.AlterField(
            model_name='ukrainestatistic',
            name='uk_doc',
            field=models.FileField(blank=True, null=True, upload_to='companies/documents/uk_statistics', verbose_name='Справка Государственного комитета статистики Украины'),
        ),
    ]
