# Generated by Django 2.1.7 on 2019-05-17 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_customuser_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bank_name',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Название банка'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='checking_account',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Рассчетный счет'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='edpnou',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='ЕДРПОУ'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='mfi',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='МФО'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='organization',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Организация'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='organizational_legal_form_of_the_company',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Организационно-правовая форма предприятия'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='payer_evidence',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Свидетельства плательщика'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='vat',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='НДС'),
        ),
    ]
