# Generated by Django 2.1.7 on 2019-05-17 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_auto_20190517_1306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='payer_evidence',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='vat',
        ),
        migrations.AddField(
            model_name='customuser',
            name='vat_payer_certificate',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Свидетельства плательщика НДС'),
        ),
    ]
