# Generated by Django 2.1.7 on 2019-05-24 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_customuser_available_products_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_pocket',
            field=models.CharField(blank=True, choices=[('NO', 'No'), ('SILVER', 'Silver'), ('GOLD', 'Gold'), ('PLATINUM', 'Platinum')], default='BASE', max_length=10, null=True, verbose_name='Пакет услуг'),
        ),
    ]
