# Generated by Django 2.1.7 on 2019-05-27 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_customuser_user_pocket'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractorProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщики',
                'proxy': True,
                'indexes': [],
            },
            bases=('users.customuser',),
        ),
        migrations.CreateModel(
            name='PartnerUserProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Продавец',
                'verbose_name_plural': 'Продавцы',
                'proxy': True,
                'indexes': [],
            },
            bases=('users.customuser',),
        ),
    ]
