# Generated by Django 2.1.7 on 2019-05-27 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_contractorproxy_partneruserproxy'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Администратор',
                'verbose_name_plural': 'Администраторы',
                'proxy': True,
                'indexes': [],
            },
            bases=('users.customuser',),
        ),
    ]
