# Generated by Django 2.1.7 on 2019-06-24 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_auto_20190612_1152'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Компания продавца', 'verbose_name_plural': 'Компании продавцов'},
        ),
        migrations.AlterModelOptions(
            name='mystore',
            options={'verbose_name': 'Магазин продавца', 'verbose_name_plural': 'Магазины продацов'},
        ),
        migrations.AlterField(
            model_name='companypitch',
            name='good_partner',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Мы классные продавцы, потому что:'),
        ),
    ]
