# Generated by Django 2.1.7 on 2019-06-24 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_auto_20190624_1443'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mystore',
            options={'verbose_name': 'Магазин продавца', 'verbose_name_plural': 'Магазины продавцов'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_pocket',
            field=models.CharField(blank=True, choices=[('SILVER', 'Silver'), ('GOLD', 'Gold'), ('PLATINUM', 'Platinum'), ('NO', 'No')], default='NO', max_length=10, null=True, verbose_name='Пакет услуг'),
        ),
    ]
