# Generated by Django 2.1.7 on 2019-06-24 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_auto_20190624_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('CONTRACTOR', 'Поставщик'), ('PARTNER', 'Продавец')], max_length=10),
        ),
    ]
