# Generated by Django 2.1.7 on 2019-06-24 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_auto_20190624_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='product_percent',
            field=models.IntegerField(blank=True, default=5, null=True, verbose_name='Процент для продавца'),
        ),
    ]
