# Generated by Django 2.1.7 on 2019-06-26 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_auto_20190624_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='percent_for_partners',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Процент для продавцов'),
        ),
    ]
