# Generated by Django 2.1.7 on 2019-06-26 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_customuser_percent_for_partners'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_pocket',
            field=models.CharField(choices=[('NO', 'No'), ('SILVER', 'Silver'), ('GOLD', 'Gold'), ('PLATINUM', 'Platinum')], default='NO', max_length=10, verbose_name='Пакет услуг'),
        ),
    ]
