# Generated by Django 2.1.7 on 2019-06-26 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_customuser_product_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='product_percent',
            field=models.SmallIntegerField(blank=True, default=5, null=True, verbose_name='Процент для продавца'),
        ),
    ]
