# Generated by Django 2.1.7 on 2019-06-26 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_customuser_product_percent'),
    ]

    operations = [

    ]
