# Generated by Django 2.1.7 on 2019-03-22 12:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageForLesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='marketplace/images_for_lessons')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(blank=True, null=True, upload_to='marketplace/video_lessons')),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name='Заголовок')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Содержание')),
                ('price', models.CharField(blank=True, max_length=20, null=True, verbose_name='Цена круса')),
                ('subscriber', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VideoLesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(blank=True, null=True, upload_to='marketplace/video_lessons')),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name='Заголовок')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Содержание')),
                ('training_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.TrainingModule')),
            ],
        ),
        migrations.AddField(
            model_name='imageforlesson',
            name='video_lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_for_lesson', to='marketplace.VideoLesson'),
        ),
    ]
