# Generated by Django 2.1.7 on 2019-04-08 12:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marketplace', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingmodule',
            name='subscriber',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='imagefortraining',
            name='video_lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_for_training', to='marketplace.VideoLesson'),
        ),
        migrations.AddField(
            model_name='imageforlesson',
            name='video_lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_for_lesson', to='marketplace.VideoLesson'),
        ),
    ]
