# Generated by Django 2.1.7 on 2019-04-08 12:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketplace', '0002_auto_20190327_1445'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='marketplace/additional_service')),
                ('title', models.TextField(blank=True, null=True, verbose_name='Заголовок')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('buyers', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='imageforlesson',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='marketplace/images_for_lessons', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='imageforlesson',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='imagefortraining',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='marketplace/images_for_lessons', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='imagefortraining',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='trainingmodule',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='marketplace/video_lessons', verbose_name='Видео'),
        ),
        migrations.AlterField(
            model_name='videolesson',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='marketplace/video_lessons', verbose_name='Видео'),
        ),
        migrations.AlterField(
            model_name='videotraining',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='marketplace/video_lessons', verbose_name='Видео'),
        ),
    ]
