# Generated by Django 2.1.7 on 2019-04-15 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_auto_20190409_0852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagefortraining',
            name='video_lesson',
        ),
        migrations.AddField(
            model_name='imagefortraining',
            name='video_training',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='image_for_training', to='marketplace.VideoTraining'),
            preserve_default=False,
        ),
    ]
