# Generated by Django 2.1.7 on 2019-05-06 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_auto_20190506_1139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='phone',
            new_name='phone_number',
        ),
    ]
