# Generated by Django 2.1.7 on 2019-05-08 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0008_auto_20190507_0822'),
    ]

    operations = [
        migrations.CreateModel(
            name='PocketPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название пакета')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена пакета')),
                ('currency', models.CharField(default='UAH', max_length=10, verbose_name='Валюта')),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Пакет услуг',
                'verbose_name_plural': 'Пакеты услуг',
            },
        ),
    ]
