# Generated by Django 2.1.7 on 2019-05-13 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0008_auto_20190507_0822'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainingmodule',
            options={'verbose_name': 'Обучающий модуль', 'verbose_name_plural': 'Обучающие модули'},
        ),
        migrations.AlterModelOptions(
            name='videolesson',
            options={'verbose_name': 'Видео урок', 'verbose_name_plural': 'Видео уроки'},
        ),
        migrations.AlterModelOptions(
            name='videotraining',
            options={'verbose_name': 'Обучающее видео', 'verbose_name_plural': 'Обучающие видео'},
        ),
    ]
