# Generated by Django 2.1.7 on 2019-05-17 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0010_pocketvideo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pocketvideo',
            options={'verbose_name': 'Видео для пакетов', 'verbose_name_plural': 'Видео для пакетов'},
        ),
    ]
