# Generated by Django 2.1.7 on 2019-04-17 10:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=40, null=True, verbose_name='Заголовок')),
                ('image', models.ImageField(blank=True, null=True, upload_to='shop/about_us')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст')),
            ],
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryAndPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name='Заголовок')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст')),
            ],
        ),
        migrations.CreateModel(
            name='FooterPhoneNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона для футера')),
            ],
        ),
        migrations.CreateModel(
            name='HeaderPhoneNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона для хедера')),
            ],
        ),
        migrations.CreateModel(
            name='HowToUse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name='Заголовок')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст')),
            ],
        ),
        migrations.CreateModel(
            name='LogoWithPhones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.URLField(blank=True, null=True)),
                ('shop_name', models.CharField(blank=True, max_length=40, null=True, verbose_name='Название магазина')),
                ('first_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Контакт')),
                ('second_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Контакт')),
            ],
        ),
        migrations.CreateModel(
            name='MyStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_subdomain', models.CharField(blank=True, choices=[('DM', 'Домен'), ('SD', 'Поддомен')], max_length=2, null=True, verbose_name='Домен/поддомен')),
                ('domain_name', models.URLField(blank=True, null=True, verbose_name='Имя домена')),
                ('call_back', models.CharField(blank=True, choices=[('YES', 'Включена'), ('NO', 'Выключена')], max_length=3, null=True, verbose_name='Функция Сall-back')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='Facebook')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Instagram')),
                ('linkedin', models.URLField(blank=True, null=True, verbose_name='Linkedin')),
                ('top_sales', models.BooleanField(default=False, verbose_name='Топ продаж')),
                ('no_items', models.BooleanField(default=False, verbose_name='Без товара')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='users/company_logo', verbose_name='Логотип')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Navigation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navigation', models.CharField(blank=True, max_length=200, null=True, verbose_name='Раздел навигации')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='navigations', to='my_store.MyStore')),
            ],
        ),
        migrations.CreateModel(
            name='SocialNetwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.URLField(blank=True, max_length=100, null=True)),
                ('instagram', models.URLField(blank=True, max_length=100, null=True)),
                ('twitter', models.URLField(blank=True, max_length=100, null=True)),
                ('google', models.URLField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StoreSliderImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='users/company/store/slider', verbose_name='Картинка для слайдера')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slider_images', to='my_store.MyStore')),
            ],
        ),
        migrations.AddField(
            model_name='headerphonenumber',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='header_phones', to='my_store.MyStore'),
        ),
        migrations.AddField(
            model_name='footerphonenumber',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='footer_phones', to='my_store.MyStore'),
        ),
    ]
