# Generated by Django 2.1.7 on 2019-04-08 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='YMLTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.FileField(upload_to='yml_templates')),
                ('yml_type', models.CharField(choices=[('rozetka', 'Rozetka'), ('prom', 'Prom')], max_length=10)),
            ],
        ),
    ]
