# Generated by Django 2.1.7 on 2019-04-09 07:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(default='type1', max_length=256, verbose_name='Вид товара'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(default='brand1', max_length=255, verbose_name='Бренд'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('user', 'contractor_product', 'vendor_code')},
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
