# Generated by Django 2.1.7 on 2019-03-22 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20190321_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='catalog/products/images', verbose_name='Изображение товара'),
        ),
    ]
