# Generated by Django 2.1.7 on 2019-04-03 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0002_auto_20190403_1142'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcontractor',
            options={'verbose_name': 'Товар (как поставщик)', 'verbose_name_plural': 'Товары (как поставщик)'},
        ),
        migrations.AlterModelOptions(
            name='productpartner',
            options={'verbose_name': 'Мой товар (добавленный от поставшика)', 'verbose_name_plural': 'Мои товары (добавленные от поставщика)'},
        ),
        migrations.RemoveField(
            model_name='productcontractor',
            name='contractors',
        ),
        migrations.AddField(
            model_name='productcontractor',
            name='contractor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contractors', to=settings.AUTH_USER_MODEL, verbose_name='Поставщик'),
        ),
        migrations.AlterField(
            model_name='productpartner',
            name='partner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='партнер'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='productpartner',
            unique_together={('partner', 'product_by_contractor')},
        ),
    ]
