# Generated by Django 2.1.7 on 2019-04-09 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0002_auto_20190409_0852'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductUploadFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='catalog/product/uploads/', verbose_name='Файл для загрузки товаров')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_import_files', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Файл для импорта товаров',
                'verbose_name_plural': 'Файлы для импорта товаров',
            },
        ),
    ]
