# Generated by Django 2.1.7 on 2019-03-21 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_productimage_productimageurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='vendor_code',
            field=models.CharField(default=1, max_length=63, verbose_name='Артикул'),
            preserve_default=False,
        ),
    ]
