# Generated by Django 2.1.7 on 2019-04-09 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_productuploadfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='productuploadfile',
            name='errors',
            field=models.TextField(blank=True, null=True, verbose_name='Ошибки'),
        ),
        migrations.AddField(
            model_name='productuploadfile',
            name='is_upload',
            field=models.BooleanField(default=False, verbose_name='Загружен'),
        ),
    ]
