# Generated by Django 2.1.7 on 2019-04-09 08:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0003_remove_product_product_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='box_size',
            field=models.CharField(default='size1', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='variety_type',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Название разновидности'),
        ),
        migrations.AddField(
            model_name='product',
            name='vendor_country',
            field=models.CharField(default='US', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='warranty_duration',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('user', 'product_type', 'brand', 'name', 'variety_type', 'vendor_code')},
        ),
    ]
