# Generated by Django 2.1.7 on 2019-04-08 12:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20190401_0729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='Основной ключ'),
        ),
        migrations.AlterField(
            model_name='productcontractor',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='productpartner',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='productpartner',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Партнер'),
        ),
        migrations.AlterField(
            model_name='productpartner',
            name='product_by_contractor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.ProductContractor', verbose_name='Продукция поставщика'),
        ),
        migrations.AlterField(
            model_name='productpartnerimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.ProductPartner', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='productpartnerimageurl',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.ProductPartner', verbose_name='Товар'),
        ),
    ]
