# Generated by Django 2.1.7 on 2019-04-08 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20190408_1459'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ymltemplate',
            options={'verbose_name': 'YML шаблон', 'verbose_name_plural': 'YML шаблоны'},
        ),
    ]
