# Generated by Django 2.1.7 on 2019-04-09 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20190409_0814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='availability',
        ),
        migrations.AddField(
            model_name='product',
            name='age_group',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Возрастная группа'),
        ),
        migrations.AddField(
            model_name='product',
            name='extra_description',
            field=models.TextField(blank=True, null=True, verbose_name='Дополнительные характеристики'),
        ),
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Материал товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default='desc1', max_length=4095, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default='1', max_digits=10, verbose_name='Цена товара'),
            preserve_default=False,
        ),
    ]
