# Generated by Django 2.1.7 on 2019-04-10 12:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0004_auto_20190409_1413'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductUploadHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_uploaded', models.BooleanField(default=False, verbose_name='Загрузка прошла успешно')),
                ('errors', models.TextField(blank=True, null=True, verbose_name='Ошибки')),
                ('file', models.FileField(upload_to='catalog/product/uploads', verbose_name='XLS файл')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_import_files', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Файл для импорта товаров',
                'verbose_name_plural': 'Файлы для импорта товаров',
            },
        ),
        migrations.RemoveField(
            model_name='productuploadfile',
            name='owner',
        ),
        migrations.DeleteModel(
            name='ProductUploadFile',
        ),
    ]
