# Generated by Django 2.1.7 on 2019-03-22 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20190321_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='id - primary key'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='catalog/products/images', verbose_name='Изображение товара'),
        ),
    ]
