# Generated by Django 2.1.7 on 2019-04-10 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20190410_1252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productuploadhistory',
            old_name='file',
            new_name='xls_file',
        ),
        migrations.RemoveField(
            model_name='productuploadhistory',
            name='file_name',
        ),
    ]
