# Generated by Django 2.1.7 on 2019-04-09 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20190409_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ymltemplate',
            name='yml_type',
            field=models.CharField(choices=[('rozetka', 'Rozetka'), ('prom', 'Prom')], max_length=10),
        ),
        migrations.AddField(
            model_name='ymltemplate',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
