# Generated by Django 2.1.7 on 2019-04-09 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20190409_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='ymltemplate',
            name='products',
            field=models.ManyToManyField(to='catalog.Product'),
        ),
    ]
