# Generated by Django 2.1.7 on 2019-04-12 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_ymltemplate_products'),
        ('catalog', '0006_auto_20190410_1257'),
    ]

    operations = [
    ]
