# Generated by Django 2.1.7 on 2019-04-15 15:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0010_auto_20190412_1031'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('user', 'product_type', 'brand', 'name', 'variety_type', 'vendor_code', 'contractor_product')},
        ),
    ]
