# Generated by Django 2.1.7 on 2019-04-24 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_productuploadhistory_file_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rozetka_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
