# Generated by Django 2.1.7 on 2019-04-26 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_product_rozetka_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='productuploadhistory',
            name='imported_products_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productuploadhistory',
            name='total_products_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
