# Generated by Django 2.1.7 on 2019-05-17 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_auto_20190513_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='recommended_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Рекомендованная цена товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Розниная цена товара'),
        ),
    ]
