# Generated by Django 2.1.7 on 2019-06-24 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_auto_20190527_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(max_length=5000, null=True, verbose_name='Описание'),
        ),
    ]
