# Generated by Django 2.1.7 on 2019-06-25 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_auto_20190624_1618'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryOptionGroup',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Название параметра')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='optiongroups', to='catalog.Category')),
            ],
            options={
                'verbose_name': 'Category Option Group',
                'verbose_name_plural': 'Category Option Groups',
            },
        ),
        migrations.CreateModel(
            name='CategoryOptionGroupValue',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Значение параметра')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='optiongroupvalues', to='catalog.Category')),
            ],
            options={
                'verbose_name': 'Category Option Group value',
                'verbose_name_plural': 'Category Option Groups values',
            },
        ),
        migrations.CreateModel(
            name='ProductOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.CategoryOptionGroupValue')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_options', to='catalog.Product')),
            ],
            options={
                'verbose_name': 'Category option',
                'verbose_name_plural': 'Category options',
            },
        ),
        migrations.AlterUniqueTogether(
            name='categoryoptiongroupvalue',
            unique_together={('group', 'name')},
        ),
    ]
