# Generated by Django 2.1.7 on 2019-04-12 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('market_id', models.PositiveIntegerField()),
                ('created', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_with_discount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cost_with_discount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.PositiveSmallIntegerField()),
                ('status_group', models.PositiveSmallIntegerField()),
                ('seller_comment_created', models.DateTimeField()),
                ('current_seller_comment', models.TextField()),
                ('comment', models.TextField()),
                ('user_phone', models.CharField(max_length=32)),
                ('from_warehouse', models.PositiveSmallIntegerField()),
                ('ttn', models.CharField(max_length=32)),
                ('total_quantity', models.PositiveSmallIntegerField()),
                ('can_copy', models.BooleanField()),
                ('created_type', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OrderDelivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_service_id', models.PositiveIntegerField()),
                ('delivery_service_name', models.CharField(max_length=256)),
                ('recipient_title', models.CharField(max_length=256)),
                ('place_id', models.PositiveIntegerField()),
                ('place_street', models.CharField(max_length=1024)),
                ('place_number', models.CharField(max_length=32)),
                ('place_house', models.CharField(max_length=32)),
                ('place_flat', models.CharField(blank=True, max_length=64, null=True)),
                ('cost', models.CharField(blank=True, max_length=64, null=True)),
                ('city', models.CharField(max_length=256)),
                ('delivery_method_id', models.PositiveIntegerField()),
                ('ref_id', models.UUIDField()),
                ('name_logo', models.CharField(max_length=32)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orders.Order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItemPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.PositiveIntegerField()),
                ('url', models.URLField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderSellerComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created', models.DateTimeField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderStatusHistoryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_id', models.PositiveIntegerField()),
                ('created', models.DateTimeField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('login', models.CharField(max_length=64)),
                ('contact_fio', models.CharField(max_length=256)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orders.Order')),
            ],
        ),
    ]
