# Generated by Django 2.1.7 on 2019-04-17 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='seller_comment_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
