# Generated by Django 2.1.7 on 2019-04-17 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20190417_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdelivery',
            name='ref_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
