# Generated by Django 2.1.7 on 2019-04-25 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_order_system_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderuser',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
