# Generated by Django 2.1.7 on 2019-04-25 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20190425_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderuser',
            name='login',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
