# Generated by Django 2.1.7 on 2019-04-25 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_auto_20190425_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdelivery',
            name='place_street',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
