# Generated by Django 2.1.7 on 2019-05-13 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_auto_20190513_1346'),
    ]

    operations = [
        migrations.CreateModel(
            name='NovaPoshtaDeliveryHistoryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('status', models.CharField(max_length=512)),
                ('status_code', models.PositiveSmallIntegerField()),
                ('contractor_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.ContractorOrder')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
