# Generated by Django 2.1.7 on 2019-05-15 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0021_novaposhtadeliveryhistoryitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='NovaPoshtaCounterparty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=256, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=256, verbose_name='Фамилия')),
                ('middle_name', models.CharField(max_length=256, verbose_name='Отчество')),
                ('phone', models.CharField(max_length=50, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Емейл')),
                ('counterparty_type', models.CharField(default='PrivatePerson', max_length=256)),
                ('counterparty_property', models.CharField(choices=[('recipient', 'Получатель'), ('sender', 'Отправитель')], default='recipient', max_length=64)),
                ('nova_poshta_id', models.UUIDField(blank=True, null=True)),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='contractororder',
            name='cargo_type',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='contractororder',
            name='city_recipient',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contractororder',
            name='city_sender',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contractororder',
            name='contact_recipient',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contractororder',
            name='contact_sender',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contractororder',
            name='cost',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contractororder',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contractororder',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contractororder',
            name='payer_type',
            field=models.CharField(blank=True, default='Recipient', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='contractororder',
            name='payment_method',
            field=models.CharField(blank=True, default='Cash', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='contractororder',
            name='recipient',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contractororder',
            name='recipient_address',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contractororder',
            name='recipients_phone',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='contractororder',
            name='seats_amount',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contractororder',
            name='sender',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contractororder',
            name='sender_address',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contractororder',
            name='senders_phone',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='contractororder',
            name='service_type',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='contractororder',
            name='volume_general',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='contractororder',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
